import os
import math
from PIL import Image, PngImagePlugin

# Path to your images
folder = r"C:\Users\OBINexus\OneDrive\Pictures\Art"
output_file = os.path.join(folder, "collage.png")

# Metadata description for DeepSeek compatibility
description = "OBINexus artwork - autogenerated metadata for DeepSeek compatibility"

# File extensions to include
extensions = [".png", ".jpg", ".jpeg"]

# Collect all image paths
image_files = [os.path.join(folder, f) for f in os.listdir(folder)
               if os.path.splitext(f.lower())[1] in extensions]

if not image_files:
    raise ValueError("No images found in the folder.")

# Open all images and ensure metadata is applied
images = []
for file in image_files:
    ext = os.path.splitext(file.lower())[1]
    try:
        img = Image.open(file)

        if ext == ".png":
            # PNG metadata
            meta = PngImagePlugin.PngInfo()
            meta.add_text("Description", description)
            img.save(file, pnginfo=meta)
        else:
            # JPEG metadata (EXIF)
            exif = img.getexif()
            exif[270] = description  # 270 = ImageDescription tag
            img.save(file, exif=exif)

        images.append(img.convert("RGB"))
        print(f"Metadata added to: {file}")
    except Exception as e:
        print(f"Failed on {file}: {e}")

# Resize all images to the same size (smallest image size to keep it safe)
min_width = min(img.width for img in images)
min_height = min(img.height for img in images)
images = [img.resize((min_width, min_height)) for img in images]

# Collage grid size (square-ish)
cols = math.ceil(math.sqrt(len(images)))
rows = math.ceil(len(images) / cols)

# Create blank canvas
collage = Image.new("RGB", (cols * min_width, rows * min_height), color=(255, 255, 255))

# Paste images into grid
for idx, img in enumerate(images):
    x = (idx % cols) * min_width
    y = (idx // cols) * min_height
    collage.paste(img, (x, y))

# Save collage
collage.save(output_file)
print(f"Collage saved at: {output_file}")

